version: '3.7'
services: 
  dvwa:
    build:
      context: ./docker-compose/DVWA
      dockerfile: Dockerfile.dvwa
    container_name: dvwa_container
    restart: unless-stopped
    ports:
      - '8090:80'
    environment:
      TZ: Asia/Taipei
    # pid: "host"
    volumes: #掛載以下資料夾，用來更改dvwa頁面的各種權限，主要是將php.ini加入版控
      - ./docker-compose/DVWA/var/www:/var/www
      - ./docker-compose/DVWA/etc/php:/etc/php
      - ./docker-compose/DVWA/etc/php5:/etc/php5
    networks:
      - safe_network
    
  nginx:
    image: nginx:1.21.6-alpine
    container_name: ccoe_nginx
    restart: unless-stopped
    ports:
      - '8095:80'
    volumes:
      # - ./docker-compose/nginx:/etc/nginx/conf.d:ro
      - ./docker-compose/nginx/nginx_log:/var/log/nginx
    environment:
      TZ: Asia/Taipei
    networks:
      - safe_network


    
  falco:
    build:
      context: ./docker-compose/falco_test
      dockerfile: Dockerfile.falco
    container_name: falco_monitor
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - ./docker-compose/falco/falco_mount:/etc/falco:ro
    environment:
      TZ: Asia/Taipei
    # ports:
      # - '8096:8765'
    networks:
      - safe_network
    depends_on:
      - dvwa
      - nginx

networks:
  safe_network:
    driver: bridge
  

volumes:
  falco-rules:
    name: falco-rules
#   dvwa-var-www:
#     name: dvwa-var-www
  
#   dvwa-etc:
#     name: dvwa-etc