version: "3.7"
services:
  falco: #falco_monitor
    image: falcosecurity/falco:0.31.1
    container_name: falco_monitor
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - ./docker-compose/falco/falco_mount:/etc/falco:ro
    environment:
      TZ: Asia/Taipei
    networks:
      - safe_network

  target_machine: #靶機
    build:
      context: ./docker-compose/ubuntu_1804
      dockerfile: Dockerfile
    container_name: ubuntu_1804
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    environment:
      TZ: Asia/Taipei

  db: #存放falco logs的db
    image: postgres:12
    container_name: falco_logs_db
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRESQL_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      TZ: Asia/Taipei
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-compose/db/init.d:/docker-entrypoint-initdb.d
      - ./docker-compose/db/update-db-scripts/:/update-db-script/ #要對db進行操作就寫scripts並進去container裡面運行
    networks:
      - safe_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: ccoe-pgadmin
    restart: unless-stopped
    ports:
      - 8095:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ccoe-pgadmin:/var/lib/pgadmin
    networks:
      - safe_network
    depends_on:
      - db

  falco_python:
    build:
      context: ./docker-compose/falco_python
      dockerfile: Dockerfile.falco_python
    container_name: falco_python
    tty: true
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
    networks:
      - safe_network
    ports:
      - "8092:5000"

networks:
  safe_network:
    driver: bridge

volumes:
  db-data:
    name: db-data
  ccoe-pgadmin:
    name: ccoe-pgadmin
