FROM python:3.8

WORKDIR /app
COPY requirements.txt .

RUN set -ex \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY app.py .

CMD ["python", "-m",  "flask", "run", "--host=0.0.0.0"]