FROM python:3.8

WORKDIR /app
COPY requirements.txt .

RUN set -ex \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY .env .
COPY app.py .
COPY app ./app

CMD ["python", "-m", "flask", "--debug", "run", "--host=0.0.0.0"]