FROM python:3.8

COPY requirements.txt /app/

WORKDIR /app

RUN set -ex \
    && pip install --upgrade pip \
    && pip install -r requirements.txt
    
# 以下這個檔案得重寫 變成單純讀取falco的logs並寫進db當中
# CMD python web.py